# —————————— Profile —————————— #
# language
language: cn
# avatar
avatar:
# author
author:
# signature
signature:

# ========== Site ========== #
# title of the site
SEO_title: Mr.Long's Blog
# main title
main_title: Mr.Long's Blog
# subtitle
subtitle: Welcome to my Blog!
# 
# site haeder image
site_header_image: '/img/intro/index-bg.jpg'
# post haeder image
post_header_image:
# 404 image
_404_image:
# about image
about_header_image: 

# —————————— Indivdual —————————— #
# Miscelaneous
favicon: /favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# intro height (the default is 60 percents of the screen)
intro_height: 60

# —————————— Others —————————— #
# main menu navigation
menu:
  Home: /
  About: /about
  Category: /category
  Archives: /archives
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
# scripts loaded in the end of the body
scripts:
- /js/main.js