# —————————— Profile —————————— #
# avatar
avatar:
# author
author:
# signature
signature:

# —————————— Indivdual —————————— #
# Miscelaneous
favicon: /favicon.ico
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 

# —————————— Others —————————— #
# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
# scripts loaded in the end of the body
scripts:
- /js/main.js